const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');
function pad(n){return String(n).padStart(2,'0');}
function formatRunTimestamp(date = new Date()) { return `${pad(date.getDate())}-${pad(date.getMonth()+1)}-${date.getFullYear()}_${pad(date.getHours())}-${pad(date.getMinutes())}-${pad(date.getSeconds())}`; }
function safeName(v){ const s=String(v||'').replace(/[^A-Za-z0-9_.-]/g,'_'); if (!s || s.includes('..')) throw new Error('Niebezpieczna nazwa pliku'); return s; }
function assertInside(base, target){ const b=path.resolve(base)+path.sep; const t=path.resolve(target); if(!t.startsWith(b)) throw new Error(`Ścieżka poza katalogiem docelowym: ${target}`); }
async function ensureDir(d){ await fs.promises.mkdir(d,{recursive:true}); }
async function resolveUniqueOutputPath(directory, baseName, extension){ await ensureDir(directory); const ext = extension.startsWith('.') ? extension : `.${extension}`; const base=safeName(baseName); for(let i=0;i<1000;i++){ const suffix=i===0?'':`_${pad(i)}`; const p=path.join(directory, `${base}${suffix}${ext}`); assertInside(directory,p); try { const fh=await fs.promises.open(p,'wx'); await fh.close(); await fs.promises.rm(p,{force:true}); return p; } catch(e){ if(e.code!=='EEXIST') throw e; } } throw new Error('Nie można znaleźć unikalnej nazwy pliku'); }
async function atomicWriteFile({ sessionDir, outputDir, baseName, extension, content, type, manifest, partial=false, validate }){ await ensureDir(sessionDir); await ensureDir(outputDir); const finalPath=await resolveUniqueOutputPath(outputDir,baseName,extension); const tmp=path.join(sessionDir, `${path.basename(finalPath)}.tmp${path.extname(finalPath)}`); assertInside(sessionDir,tmp); if (Buffer.isBuffer(content) || typeof content === 'string') await fs.promises.writeFile(tmp, content); else if (typeof content === 'function') await content(tmp); const st=await fs.promises.stat(tmp); if (st.size <= 0 && type !== 'missingDates') throw new Error(`Pusty plik tymczasowy: ${type}`); if (validate) await validate(tmp); await fs.promises.rename(tmp, finalPath); const outStat=await fs.promises.stat(finalPath); const entry={type,path:finalPath,size:outStat.size,createdAt:new Date().toISOString(),partial}; manifest?.files?.push(entry); return finalPath; }
function validateXlsx(headers){ return async (filePath)=>{ const st=await fs.promises.stat(filePath); if(!st.size) throw new Error('XLSX jest pusty'); const wb=XLSX.readFile(filePath); if(!wb.SheetNames.includes('albums')) throw new Error('Brak arkusza albums'); const rows=XLSX.utils.sheet_to_json(wb.Sheets.albums,{header:1,defval:''}); const first=rows[0]||[]; for(const h of headers){ if(!first.includes(h)) throw new Error(`Brak nagłówka XLSX: ${h}`); } }; }
module.exports={formatRunTimestamp,resolveUniqueOutputPath,atomicWriteFile,validateXlsx,ensureDir,assertInside};
