const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  fetchWorkbook: () => ipcRenderer.invoke("fetch-workbook"),
  updateWorkbook: (payload = {}) => ipcRenderer.invoke("update-workbook", payload),
  exportXlsx: (payload = {}) => ipcRenderer.invoke("export-xlsx", payload),
  importXlsx: (payload = {}) => ipcRenderer.invoke("import-xlsx", payload),
  importNewsXlsx: (payload = {}) => ipcRenderer.invoke("import-news-xlsx", payload),
  importJson: (payload = {}) => ipcRenderer.invoke("import-json", payload),
  runQobuzScraper: (payload = {}) => ipcRenderer.invoke("run-qobuz-scraper", payload),
  selectDirectory: (payload = {}) => ipcRenderer.invoke("select-directory", payload),
  selectFile: (payload = {}) => ipcRenderer.invoke("select-file", payload),
  getAppDirectory: () => ipcRenderer.invoke("get-app-directory"),
  resolveImportFile: (payload = {}) => ipcRenderer.invoke("resolve-import-file", payload),
  resolveJsonFile: (payload = {}) => ipcRenderer.invoke("resolve-json-file", payload),
  saveFile: (payload) => ipcRenderer.invoke("save-file", payload),
  readTextFile: (payload = {}) => ipcRenderer.invoke("read-text-file", payload),
  checkFileExists: (payload = {}) => ipcRenderer.invoke("check-file-exists", payload),
  backupDatabase: () => ipcRenderer.invoke("backup-database"),
  checkDatabase: (payload = {}) => ipcRenderer.invoke("check-database", payload),
  deleteAlbumAssets: (payload = {}) => ipcRenderer.invoke("delete-album-assets", payload),
  fetchFilterPresets: () => ipcRenderer.invoke("fetch-filter-presets"),
  saveFilterPreset: (payload = {}) => ipcRenderer.invoke("save-filter-preset", payload),
  renameFilterPreset: (payload = {}) => ipcRenderer.invoke("rename-filter-preset", payload),
  deleteFilterPreset: (payload = {}) => ipcRenderer.invoke("delete-filter-preset", payload),
  isProcessRunning: (payload = {}) => ipcRenderer.invoke("is-process-running", payload),
  onImportJsonProgress: (handler) => ipcRenderer.on("import-json-progress", handler),
  removeImportJsonProgress: (handler) => ipcRenderer.removeListener("import-json-progress", handler),
  onQobuzScrapeProgress: (handler) => ipcRenderer.on("qobuz-scrape-progress", handler),
  removeQobuzScrapeProgress: (handler) => ipcRenderer.removeListener("qobuz-scrape-progress", handler),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  maximizeTidalWindow: () => ipcRenderer.invoke("maximize-tidal-window"),
  onAppCloseRequest: (handler) => ipcRenderer.on("app-close-request", handler),
  confirmAppClose: () => ipcRenderer.send("app-close-confirmed")
});